<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matthew Roohan (mlr287), Aishwarya Gupta (ag2469), Ryun Shim, Helena Xiong">

<title>Go Fund Me Data Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="gfm_data_analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="gfm_data_analysis_files/libs/quarto-html/quarto.js"></script>
<script src="gfm_data_analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="gfm_data_analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="gfm_data_analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="gfm_data_analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="gfm_data_analysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="gfm_data_analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="gfm_data_analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="gfm_data_analysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Go Fund Me Data Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Matthew Roohan (mlr287), Aishwarya Gupta (ag2469), Ryun Shim, Helena Xiong </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="data-and-packages" class="level2">
<h2 class="anchored" data-anchor-id="data-and-packages">Data and packages</h2>
<p>We start with loading the packages we’ll use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidytext)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: NLP

Attaching package: 'NLP'

The following object is masked from 'package:ggplot2':

    annotate</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(SnowballC)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wordcloud)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: RColorBrewer</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(syuzhet)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>randomForest 4.7-1.1
Type rfNews() to see new features/changes/bug fixes.

Attaching package: 'randomForest'

The following object is masked from 'package:dplyr':

    combine

The following object is masked from 'package:ggplot2':

    margin</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caTools)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(maps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'maps'

The following object is masked from 'package:purrr':

    map</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'scales'

The following object is masked from 'package:syuzhet':

    rescale

The following object is masked from 'package:purrr':

    discard

The following object is masked from 'package:readr':

    col_factor</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>gfm_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/gfm_cleaned_data.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-analysis-components" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis-components">Data Analysis Components:</h2>
<ul>
<li><p>Fundraising Goals and Donor Engagement</p>
<ul>
<li><p>How do different initial fundraising goals impact the number of donations received and donor engagement on GoFundMe?”</p></li>
<li><p>Do campaigns with higher initial fundraising goals tend to receive more donations, or do more modest goals attract greater donor engagement?</p></li>
<li><p>To what extent do campaigns with personalized stories or unique appeals attract more donors and achieve higher fundraising goals compared to campaigns with generic messages?</p></li>
</ul></li>
<li><p>Social Media Pattern &amp; Geographical Pattern</p>
<ul>
<li><p>What is the correlation between social media engagement metrics (likes, shares, comments) and the amount of funds raised in GoFundMe campaigns?”</p></li>
<li><p>Are there discernible geographic patterns in campaign success on GoFundMe? Do campaigns in specific regions or cities tend to achieve higher fundraising goals?</p></li>
</ul></li>
<li><p>Time analysis:</p>
<ul>
<li>How does the length of the fundraising campaign impact its success? Are longer or shorter campaigns more effective in reaching their funding goals?’</li>
</ul></li>
</ul>
</section>
<section id="time-analysis" class="level2">
<h2 class="anchored" data-anchor-id="time-analysis">Time Analysis:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#was the goal reached or not?</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>gfm_data<span class="sc">$</span>goal_reached <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(gfm_data<span class="sc">$</span>amount_raised <span class="sc">&gt;=</span>gfm_data<span class="sc">$</span>goal, <span class="st">"Yes"</span>, <span class="st">"No"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating time analysis dataset </span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>time_analysis <span class="ot">&lt;-</span> <span class="fu">select</span>(gfm_data, category, position, amount_raised, goal, number_of_donators, campaign_length_days, goal_reached)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co">#clean dataset </span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>time_analysis <span class="ot">&lt;-</span> time_analysis[<span class="fu">complete.cases</span>(time_analysis<span class="sc">$</span>campaign_length_days, time_analysis<span class="sc">$</span>goal_reached), ]</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co">#graph analysis</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>time_analysis<span class="sc">$</span>goal_reached <span class="ot">&lt;-</span> <span class="fu">factor</span>(time_analysis<span class="sc">$</span>goal_reached, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a boxplot to compare campaign lengths for goal reached and not reached campaigns</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_analysis, <span class="fu">aes</span>(<span class="at">x =</span> goal_reached, <span class="at">y =</span> campaign_length_days, <span class="at">fill =</span> goal_reached)) <span class="sc">+</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Goal Reached"</span>, <span class="at">y =</span> <span class="st">"Campaign Length (Days)"</span>,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Impact of Campaign Length on Goal Achievement"</span>) <span class="sc">+</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="gfm_data_analysis_files/figure-html/time-analysis-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>Both Yes and No Goal reached have very similar</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>time_analysis<span class="sc">$</span>goal_reached <span class="ot">&lt;-</span> <span class="fu">factor</span>(time_analysis<span class="sc">$</span>goal_reached, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate counts for each unique combination of "campaign_length_days" and "goal_reached"</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>aggregated_data <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(goal_reached <span class="sc">~</span> campaign_length_days, <span class="at">data =</span> time_analysis, <span class="at">FUN =</span> table)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the columns</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(aggregated_data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Campaign_Length_Days"</span>, <span class="st">"Counts"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Split "Counts" column into separate columns for "No" and "Yes"</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>aggregated_data <span class="ot">&lt;-</span> <span class="fu">cbind</span>(aggregated_data, <span class="fu">as.data.frame</span>(aggregated_data<span class="sc">$</span>Counts))</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the original "Counts" column</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>aggregated_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(aggregated_data, <span class="at">select =</span> <span class="sc">-</span>Counts)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the columns for "No" and "Yes"</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(aggregated_data)[<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"No_Count"</span>, <span class="st">"Yes_Count"</span>)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>aggregated_data<span class="sc">$</span>yes_probability <span class="ot">&lt;-</span> aggregated_data<span class="sc">$</span>Yes_Count <span class="sc">/</span> (aggregated_data<span class="sc">$</span>No_Count <span class="sc">+</span> aggregated_data<span class="sc">$</span>Yes_Count)</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the new dataframe</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(aggregated_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Campaign_Length_Days No_Count Yes_Count yes_probability
1                     7        2         0       0.0000000
2                     8        3         2       0.4000000
3                     9        5         0       0.0000000
4                    10        3         1       0.2500000
5                    11        1         1       0.5000000
6                    12        4         2       0.3333333
7                    13        4         1       0.2000000
8                    14        2         2       0.5000000
9                    15        1         4       0.8000000
10                   16        4         2       0.3333333
11                   17        1         3       0.7500000
12                   18        2         3       0.6000000
13                   19        1         1       0.5000000
14                   20        1         1       0.5000000
15                   21        2         2       0.5000000
16                   22        5         3       0.3750000
17                   23        5         3       0.3750000
18                   24        2         2       0.5000000
19                   25        2         2       0.5000000
20                   26        2         3       0.6000000
21                   27        3         3       0.5000000
22                   28        3         1       0.2500000
23                   29        6         0       0.0000000
24                   30      139        76       0.3534884
25                   60      138        84       0.3783784
26                   90      101        95       0.4846939
27                  120      139        64       0.3152709
28                  150      146        78       0.3482143
29                  180       49        16       0.2461538</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming "aggregated_data" is your dataframe</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the ranges for each group of campaign lengths</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>breaks <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7</span>, <span class="dv">14</span>, <span class="dv">21</span>, <span class="dv">30</span>, <span class="dv">60</span>, <span class="dv">90</span>, <span class="dv">120</span>, <span class="dv">150</span>, <span class="dv">180</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column for the groups</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>aggregated_data<span class="sc">$</span>weeks <span class="ot">&lt;-</span> <span class="fu">cut</span>(aggregated_data<span class="sc">$</span>Campaign_Length_Days, <span class="at">breaks =</span> breaks, <span class="at">labels =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate data based on the groups</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>aggregated_month_data <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(<span class="fu">cbind</span>(No_Count, Yes_Count) <span class="sc">~</span> weeks, <span class="at">data =</span> aggregated_data, <span class="at">FUN =</span> sum)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>aggregated_month_data[<span class="dv">5</span>, <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">8</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>aggregated_month_data[<span class="dv">6</span>, <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">12</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>aggregated_month_data[<span class="dv">7</span>, <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">16</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>aggregated_month_data[<span class="dv">8</span>, <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>aggregated_month_data[<span class="dv">9</span>, <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">24</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(aggregated_month_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  weeks No_Count Yes_Count
1     1        2         0
2     2       22         9
3     3       12        16
4     4      167        93
5     8      138        84
6    12      101        95
7    16      139        64
8    20      146        78
9    24       49        16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>aggregated_month_data<span class="sc">$</span>yes_probability <span class="ot">&lt;-</span> aggregated_month_data<span class="sc">$</span>Yes_Count <span class="sc">/</span> (aggregated_month_data<span class="sc">$</span>No_Count <span class="sc">+</span> aggregated_month_data<span class="sc">$</span>Yes_Count)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a line plot</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(aggregated_month_data, <span class="fu">aes</span>(<span class="at">x =</span> weeks, <span class="at">y =</span> yes_probability)) <span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fu">min</span>(aggregated_month_data<span class="sc">$</span>weeks), <span class="fu">max</span>(aggregated_month_data<span class="sc">$</span>weeks), <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Weeks"</span>, <span class="at">y =</span> <span class="st">"Goal Reached Probability"</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Goal Reached Probability over Weeks"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="gfm_data_analysis_files/figure-html/time-analysis-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="social-media-analysis" class="level2">
<h2 class="anchored" data-anchor-id="social-media-analysis">Social Media Analysis:</h2>
<ul>
<li>What is the correlation between social media engagement metrics (likes, shares, comments) and the amount of funds raised in GoFundMe campaigns?”</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating dataset </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>sm_analysis_data <span class="ot">&lt;-</span> <span class="fu">select</span>(gfm_data, amount_raised, goal, goal_reached, FB_shares, GFM_hearts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Does the number of FB_shares or GFM_hearts impact the amount that is raised?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#scatter plot for FB_shares vs. amount_raised </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm_analysis_data, <span class="fu">aes</span>(<span class="at">x =</span> FB_shares, <span class="at">y =</span> amount_raised)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">dollar_format</span>()) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Facebook Share Amount"</span>, <span class="at">y =</span> <span class="st">"Amount Raised"</span>, <span class="at">title =</span> <span class="st">"FB Shares vs Amount Raised"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 46 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="gfm_data_analysis_files/figure-html/social-media-analysis-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>The previous graph is hard to interpret, therefore use of log transformation is appropriate:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the scatter plot with logarithmic transformations</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm_analysis_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">log</span>(FB_shares <span class="sc">+</span> <span class="dv">1</span>), <span class="at">y =</span> <span class="fu">log</span>(amount_raised <span class="sc">+</span> <span class="dv">1</span>))) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Log(FB Shares)"</span>, <span class="at">y =</span> <span class="st">"Log(Amount Raised)"</span>, <span class="at">title =</span> <span class="st">"FB Shares vs. Amount Raised with a Log Transformation Applied"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 46 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 46 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="gfm_data_analysis_files/figure-html/social-media-analysis-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>The graph above shows that there is a positive correlation between FB shares and the amount that is raised.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#sm analysis with outliers removed </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>sm_no_outliers <span class="ot">&lt;-</span> <span class="fu">subset</span>(sm_analysis_data, GFM_hearts <span class="sc">&lt;</span> <span class="dv">20000</span>) </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co">#scatter plot for GFM_hearts vs. amount_raised </span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm_no_outliers, <span class="fu">aes</span>(<span class="at">x =</span> GFM_hearts, <span class="at">y =</span> amount_raised)) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">dollar_format</span>()) <span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Go Fund Me Hearts Amount"</span>, <span class="at">y =</span> <span class="st">"Amount Raised"</span>, <span class="at">title =</span> <span class="st">"GFM Hearts Amount vs Amount Raised"</span>, <span class="at">caption =</span> <span class="st">"Outliers Removed"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 3 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 3 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="gfm_data_analysis_files/figure-html/social-media-analysis-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>The graph shows that there is a positive correlation between the number of Go Fund Me hearts and the Amount that the campaign raises.</li>
</ul>
</section>
<section id="geographical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="geographical-analysis">Geographical Analysis:</h2>
<ul>
<li>Are there discernible geographic patterns in campaign success on GoFundMe? Do campaigns in specific regions or cities tend to achieve higher fundraising goals?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>geo_analysis_data <span class="ot">&lt;-</span> <span class="fu">select</span>(gfm_data, location, latitude, longitude, amount_raised, goal, goal_reached, FB_shares, GFM_hearts)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>geo_analysis_data <span class="ot">&lt;-</span> geo_analysis_data[<span class="sc">!</span><span class="fu">is.na</span>(geo_analysis_data<span class="sc">$</span>goal_reached) <span class="sc">&amp;</span> geo_analysis_data<span class="sc">$</span>goal_reached <span class="sc">!=</span> <span class="st">""</span>, ]</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>geo_analysis_data <span class="ot">&lt;-</span> geo_analysis_data <span class="sc">|&gt;</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(longitude <span class="sc">&gt;=</span> <span class="sc">-</span><span class="dv">140</span> <span class="sc">&amp;</span> latitude <span class="sc">&gt;=</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>usa <span class="ot">&lt;-</span> <span class="fu">map_data</span>(<span class="st">"usa"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_polygon</span>(<span class="at">data =</span> usa, <span class="fu">aes</span>(<span class="at">x =</span> long, <span class="at">y =</span> lat, <span class="at">group =</span> group), <span class="at">fill =</span> <span class="st">"lightgrey"</span>) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> geo_analysis_data, <span class="fu">aes</span>(<span class="at">x =</span> longitude, <span class="at">y =</span> latitude, <span class="at">size =</span> amount_raised, <span class="at">color =</span> goal_reached), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Yes"</span> <span class="ot">=</span> <span class="st">"green"</span>, <span class="st">"No"</span> <span class="ot">=</span> <span class="st">"red"</span>), <span class="at">name =</span> <span class="st">"Goal Reached"</span>) <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size</span>(<span class="at">name =</span> <span class="st">"Amount Raised"</span>, <span class="at">labels =</span> <span class="fu">label_dollar</span>()) <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_fixed</span>(<span class="fl">1.3</span>) <span class="sc">+</span>  <span class="co"># Adjusts the aspect ratio to keep the map looking like the USA</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"USA Map with Points Colored and Sized by Goal Reached"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="gfm_data_analysis_files/figure-html/geographical-analysis-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="text-analysis" class="level2">
<h2 class="anchored" data-anchor-id="text-analysis">Text Analysis:</h2>
<ul>
<li>Can the language used in the title and text of the campaign (such as sentiment, keywords, urgency) be linked to its success? Are there common themes or words in the most successful campaigns?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>TextDoc <span class="ot">&lt;-</span> <span class="fu">VCorpus</span>(<span class="fu">VectorSource</span>(gfm_data<span class="sc">$</span>text))</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the text to lower case</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>TextDoc <span class="ot">&lt;-</span> <span class="fu">tm_map</span>(TextDoc, <span class="fu">content_transformer</span>(tolower))</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove numbers</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>TextDoc <span class="ot">&lt;-</span> <span class="fu">tm_map</span>(TextDoc, removeNumbers)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove english common stopwords</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>TextDoc <span class="ot">&lt;-</span> <span class="fu">tm_map</span>(TextDoc, removeWords, <span class="fu">stopwords</span>(<span class="st">"english"</span>))</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>TextDoc <span class="ot">&lt;-</span> <span class="fu">tm_map</span>(TextDoc, removeWords, <span class="fu">c</span>(<span class="st">"go fund me"</span>)) </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove punctuations</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>TextDoc <span class="ot">&lt;-</span> <span class="fu">tm_map</span>(TextDoc, removePunctuation)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Eliminate extra white spaces</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>TextDoc <span class="ot">&lt;-</span> <span class="fu">tm_map</span>(TextDoc, stripWhitespace)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Text stemming - which reduces words to their root form</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>TextDoc <span class="ot">&lt;-</span> <span class="fu">tm_map</span>(TextDoc, stemDocument)</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Build a term-document matrix</span></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>TextDoc_dtm <span class="ot">&lt;-</span> <span class="fu">TermDocumentMatrix</span>(TextDoc)</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>dtm_m <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(TextDoc_dtm)</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort by descearing value of frequency</span></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>dtm_v <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">rowSums</span>(dtm_m),<span class="at">decreasing=</span><span class="cn">TRUE</span>)</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>dtm_d <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">word =</span> <span class="fu">names</span>(dtm_v),<span class="at">freq=</span>dtm_v)</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the top 5 most frequent words</span></span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dtm_d, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           word freq
help       help 1675
need       need 1415
today     today 1270
famili   famili  456
fund       fund  359
year       year  356
will       will  310
friend   friend  261
love       love  233
support support  233</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(dtm_d[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,]<span class="sc">$</span>freq, <span class="at">las =</span> <span class="dv">2</span>, <span class="at">names.arg =</span> dtm_d[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,]<span class="sc">$</span>word,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span><span class="st">"lightgreen"</span>, <span class="at">main =</span><span class="st">"Top 10 most frequent words"</span>,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Word frequencies"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="gfm_data_analysis_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br>
</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wordcloud</span>(<span class="at">words =</span> dtm_d<span class="sc">$</span>word, <span class="at">freq =</span> dtm_d<span class="sc">$</span>freq, <span class="at">min.freq =</span> <span class="dv">5</span>,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">max.words=</span><span class="dv">100</span>, <span class="at">random.order=</span><span class="cn">FALSE</span>, <span class="at">rot.per=</span><span class="fl">0.40</span>, </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">colors=</span><span class="fu">brewer.pal</span>(<span class="dv">8</span>, <span class="st">"Dark2"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="gfm_data_analysis_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>Can sentiment analysis of campaign descriptions provide insights into campaign success on GoFundMe? How do positive or negative sentiments affect donor engagement and fundraising outcomes?”</li>
</ul>
</section>
<section id="fundraising-goals-and-donor-engagement-analysis" class="level2">
<h2 class="anchored" data-anchor-id="fundraising-goals-and-donor-engagement-analysis">Fundraising Goals and Donor Engagement Analysis:</h2>
<ul>
<li><p>How do different initial fundraising goals impact the number of donations received and donor engagement on GoFundMe?</p></li>
<li><p>Are there certain categories of campaigns that perform better than others?</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>gfm_cleaned_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/gfm_cleaned_data.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="how-do-different-initial-fundraising-goals-impact-the-number-of-donations-received-and-donor-engagement-on-gofundme" class="level2">
<h2 class="anchored" data-anchor-id="how-do-different-initial-fundraising-goals-impact-the-number-of-donations-received-and-donor-engagement-on-gofundme">How do different initial fundraising goals impact the number of donations received and donor engagement on GoFundMe?</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values in the goal and number_of_donators variables</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(gfm_cleaned_data<span class="sc">$</span>goal))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(gfm_cleaned_data<span class="sc">$</span>number_of_donators))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove rows with missing values in 'goal' and 'number_of_donators'</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>gfm_cleaned_data_1 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(gfm_cleaned_data[, <span class="fu">c</span>(<span class="st">"goal"</span>, <span class="st">"number_of_donators"</span>)])</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if missing values are removed</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(gfm_cleaned_data_1<span class="sc">$</span>goal))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(gfm_cleaned_data_1<span class="sc">$</span>number_of_donators))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation analysis between initial fundraising goals and number of donations</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>correlation_donations <span class="ot">&lt;-</span> <span class="fu">cor</span>(gfm_cleaned_data_1<span class="sc">$</span>goal, gfm_cleaned_data_1<span class="sc">$</span>number_of_donators)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>correlation_donations</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5419016</code></pre>
</div>
</div>
<p><em>Removing rows with missing values can have several implications</em>:</p>
<p><em>Reduced Sample Size:</em> Removing rows with missing values decreases the size of your dataset, which can reduce the statistical power of your analysis. A smaller sample size may lead to less reliable estimates and wider confidence intervals.</p>
<p><em>Bias:</em> If the missing values are not completely at random (MCAR) and are related to the variables being analyzed, removing them can introduce bias into your analysis. This bias can distort the relationships between variables and lead to erroneous conclusions.</p>
<p><em>Loss of Information:</em> By removing rows with missing values, you lose information that could potentially be valuable for your analysis. This loss of information can reduce the completeness of your dataset and limit the insights that can be gained from it.</p>
<p><em>Misrepresentation of Results:</em> Removing missing values can alter the distribution and characteristics of your data, potentially leading to a misrepresentation of the true population characteristics. This misrepresentation can affect the generalizability of your results.</p>
<p><em>Assumption Violation:</em> Some statistical methods assume that the data are complete and free of missing values. Removing missing values to satisfy these assumptions may violate the integrity of your analysis and lead to invalid results.</p>
</section>
<section id="correlation-analysis-results" class="level2">
<h2 class="anchored" data-anchor-id="correlation-analysis-results">correlation analysis results</h2>
<p>A correlation coefficient of approximately 0.5419 indicates a moderate positive correlation between the initial fundraising goals and the number of donations received on GoFundMe. Here’s how you can interpret this correlation coefficient:</p>
<p><em>Strength of the Relationship:</em> The correlation coefficient ranges from -1 to 1. A value of 0.5419 suggests a moderate positive relationship between initial fundraising goals and the number of donations. This indicates that as the initial fundraising goals increase, the number of donations tends to increase as well, and vice versa.</p>
<p><em>Direction of the Relationship:</em> The positive sign indicates that as one variable (initial fundraising goals) increases, the other variable (number of donations) tends to increase as well. In other words, campaigns with higher initial fundraising goals tend to attract more donations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear regression analysis</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>linear_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(number_of_donators <span class="sc">~</span> goal, <span class="at">data =</span> gfm_cleaned_data)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the linear model</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = number_of_donators ~ goal, data = gfm_cleaned_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-15512.8   -203.9   -142.2     -0.1  30886.7 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1.742e+02  5.099e+01   3.416 0.000656 ***
goal        4.951e-03  2.190e-04  22.604  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1683 on 1229 degrees of freedom
  (7 observations deleted due to missingness)
Multiple R-squared:  0.2937,    Adjusted R-squared:  0.2931 
F-statistic: 510.9 on 1 and 1229 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The linear regression model results provide insights into the relationship between the initial fundraising goals and the number of donators on GoFundMe.</p>
<p><em>Intercept:</em> The intercept represents the expected number of donators when the initial fundraising goal is zero. In this case, the intercept is approximately 174.2 (rounded from 1.742e+02). This intercept value may not have practical meaning since initial fundraising goals are unlikely to be zero in real-world scenarios.</p>
<p><em>Coefficients:</em> The coefficient for the goal variable represents the change in the number of donators for a one-unit increase in the initial fundraising goal. For every one-unit increase in the initial fundraising goal, the number of donators is expected to increase by approximately 0.005 (rounded from 4.951e-03). The coefficient is highly significant (p-value &lt; 2e-16), indicating a strong association between the initial fundraising goal and the number of donators.</p>
<p><em>Residuals:</em> Residuals represent the differences between the observed values and the values predicted by the regression model. The residuals have a mean close to zero, indicating that the model is unbiased on average. The range of residuals indicates the spread of errors around the regression line.</p>
<p><em>Model Fit:</em> The adjusted R-squared value (0.2931) indicates that approximately 29.31% of the variation in the number of donators can be explained by the initial fundraising goals. The F-statistic (510.9) is significant (p-value &lt; 2.2e-16), suggesting that the regression model as a whole is statistically significant in explaining the relationship between the variables.</p>
<p><em>Overall Interpretation:</em> The linear regression model suggests that there is a statistically significant positive relationship between the initial fundraising goals and the number of donators on GoFundMe. However, it’s important to note that the model’s explanatory power (adjusted R-squared) is relatively low, indicating that other factors not included in the model may also influence the number of donators.</p>
<p>Additionally, while the relationship is statistically significant, the coefficient for the goal variable is small, suggesting that the practical significance of the relationship may be limited.</p>
<p>In conclusion, while the model indicates a significant association between initial fundraising goals and the number of donators, further investigation into additional factors influencing donation behavior may provide a more comprehensive understanding of donor engagement on GoFundMe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a custom theme for the plot</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>custom_theme <span class="ot">&lt;-</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>),</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>)</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting initial fundraising goals vs. number of donations with improved aesthetics</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gfm_cleaned_data, <span class="fu">aes</span>(<span class="at">x =</span> goal, <span class="at">y =</span> number_of_donators)) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"grey2"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"salmon"</span>) <span class="sc">+</span>  </span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Initial Fundraising Goal ($)"</span>, <span class="at">y =</span> <span class="st">"Number of Donations"</span>) <span class="sc">+</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Initial Fundraising Goal vs. Number of Donations"</span>) <span class="sc">+</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> dollar) <span class="sc">+</span>  </span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  custom_theme  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 7 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 7 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="gfm_data_analysis_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove missing values from 'goal', 'GFM_hearts', and "FB_shares" variables</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>complete_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(gfm_cleaned_data[, <span class="fu">c</span>(<span class="st">"goal"</span>, <span class="st">"GFM_hearts"</span>, <span class="st">"FB_shares"</span>)])</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation analysis between initial fundraising goals and donor engagement (GFM hearts)</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>correlation_engagement_hearts <span class="ot">&lt;-</span> <span class="fu">cor</span>(complete_data<span class="sc">$</span>goal, complete_data<span class="sc">$</span>GFM_hearts, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>correlation_engagement_hearts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5414683</code></pre>
</div>
</div>
<p>With a correlation coefficient of approximately 0.5415, the interpretation remains largely the same:</p>
<p><em>Strength of the Relationship:</em> The correlation coefficient of 0.5415 still indicates a moderate positive relationship between the initial fundraising goals and donor engagement (represented by the GFM_hearts variable). This suggests that as the initial fundraising goals increase, the donor engagement tends to increase as well, and vice versa.</p>
<p><em>Direction of the Relationship:</em> The positive sign indicates that as one variable (initial fundraising goals) increases, the other variable (donor engagement) tends to increase as well. In other words, campaigns with higher initial fundraising goals tend to attract more donor engagement in terms of GFM hearts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation analysis between initial fundraising goals and donor engagement (FB_shares)</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>correlation_engagement_shares <span class="ot">&lt;-</span> <span class="fu">cor</span>(complete_data<span class="sc">$</span>goal, complete_data<span class="sc">$</span>FB_shares, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>correlation_engagement_shares</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4647916</code></pre>
</div>
</div>
<p>With a correlation coefficient of approximately 0.4648:</p>
<p><em>Strength of the Relationship:</em> The correlation coefficient of 0.4648 indicates a moderate positive relationship between the initial fundraising goals and donor engagement through Facebook shares. This suggests that as the initial fundraising goals increase, the number of Facebook shares tends to increase as well, and vice versa.</p>
<p><em>Direction of the Relationship:</em> The positive sign indicates that as one variable (initial fundraising goals) increases, the other variable (Facebook shares) tends to increase as well. In other words, campaigns with higher initial fundraising goals tend to attract more donor engagement in terms of Facebook shares.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear regression analysis for donor engagement (GFM_hearts)</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>linear_model_engagement_hearts <span class="ot">&lt;-</span> <span class="fu">lm</span>(GFM_hearts <span class="sc">~</span> goal, <span class="at">data =</span> complete_data)  </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the linear model for donor engagement</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model_engagement_hearts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = GFM_hearts ~ goal, data = complete_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-15779.6   -219.7   -151.9      2.2  30754.7 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1.853e+02  5.319e+01   3.485 0.000511 ***
goal        5.033e-03  2.265e-04  22.217  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1726 on 1190 degrees of freedom
Multiple R-squared:  0.2932,    Adjusted R-squared:  0.2926 
F-statistic: 493.6 on 1 and 1190 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The linear regression model for donor engagement (represented by GFM_hearts) yields the following results:</p>
<p><em>Intercept:</em> The intercept of approximately 185.3 (rounded from 1.853e+02) indicates the estimated number of GFM hearts when the initial fundraising goal is zero. However, this value may not have practical meaning, as initial fundraising goals are unlikely to be zero.</p>
<p><em>Goal Coefficient:</em> The coefficient for the goal variable is approximately 0.005 (rounded from 5.033e-03). This means that for every one-unit increase in the initial fundraising goal, the number of GFM hearts is expected to increase by approximately 0.005.</p>
<p><em>Significance:</em> Both the intercept and the coefficient for the goal variable are highly significant (p-value &lt; 0.001), indicating a strong association between the initial fundraising goals and donor engagement (GFM hearts).</p>
<p><em>Model Fit:</em> The adjusted R-squared value is 0.2926, indicating that approximately 29.26% of the variation in donor engagement (GFM hearts) can be explained by the initial fundraising goals. The F-statistic is significant (p-value &lt; 0.001), suggesting that the regression model as a whole is statistically significant in explaining the relationship between the variables.</p>
<p><em>Residuals:</em> The residuals have a mean close to zero, indicating that the model is unbiased on average. The residual standard error is approximately 1726, indicating the average distance that the observed values deviate from the predicted values.</p>
<p>In summary, the linear regression model suggests that there is a statistically significant positive relationship between the initial fundraising goals and donor engagement (GFM hearts). However, the explanatory power of the model (adjusted R-squared) is relatively low, indicating that other factors not included in the model may also influence donor engagement behavior. Further analysis and interpretation within the context of your dataset and domain knowledge are recommended for a comprehensive understanding of the relationship between these variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear regression analysis for donor engagement (FB_shares)</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>linear_model_engagement_shares <span class="ot">&lt;-</span> <span class="fu">lm</span>(FB_shares <span class="sc">~</span> goal, <span class="at">data =</span> complete_data)  </span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the linear model for donor engagement</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model_engagement_shares)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FB_shares ~ goal, data = complete_data)

Residuals:
   Min     1Q Median     3Q    Max 
-35137   -893   -709   -121  74109 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 8.102e+02  1.436e+02   5.643 2.08e-08 ***
goal        1.107e-02  6.115e-04  18.108  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4658 on 1190 degrees of freedom
Multiple R-squared:  0.216, Adjusted R-squared:  0.2154 
F-statistic: 327.9 on 1 and 1190 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The linear regression model for donor engagement (represented by FB_shares) yields the following results:</p>
<p><em>Intercept:</em> The intercept of approximately 810.2 (rounded from 8.102e+02) indicates the estimated number of Facebook shares when the initial fundraising goal is zero. However, this value may not have practical meaning, as initial fundraising goals are unlikely to be zero.</p>
<p><em>Goal Coefficient:</em> The coefficient for the goal variable is approximately 0.0111 (rounded from 1.107e-02). This means that for every one-unit increase in the initial fundraising goal, the number of Facebook shares is expected to increase by approximately 0.0111.</p>
<p><em>Significance:</em> Both the intercept and the coefficient for the goal variable are highly significant (p-value &lt; 0.001), indicating a strong association between the initial fundraising goals and donor engagement (Facebook shares).</p>
<p><em>Model Fit:</em> The adjusted R-squared value is 0.2154, indicating that approximately 21.54% of the variation in donor engagement (Facebook shares) can be explained by the initial fundraising goals. The F-statistic is significant (p-value &lt; 0.001), suggesting that the regression model as a whole is statistically significant in explaining the relationship between the variables.</p>
<p><em>Residuals:</em> The residuals have a mean close to zero, indicating that the model is unbiased on average. The residual standard error is approximately 4658, indicating the average distance that the observed values deviate from the predicted values.</p>
<p>In summary, the linear regression model suggests that there is a statistically significant positive relationship between the initial fundraising goals and donor engagement (Facebook shares). However, similar to the previous model, the explanatory power of the model (adjusted R-squared) is relatively low, indicating that other factors not included in the model may also influence donor engagement behavior. Further analysis and interpretation within the context of your dataset and domain knowledge are recommended for a comprehensive understanding of the relationship between these variables.</p>
</section>
<section id="are-there-certain-categories-of-campaigns-that-perform-better-than-others" class="level2">
<h2 class="anchored" data-anchor-id="are-there-certain-categories-of-campaigns-that-perform-better-than-others">Are there certain categories of campaigns that perform better than others?</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group data by category and calculate aggregate statistics</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>category_performance <span class="ot">&lt;-</span> gfm_cleaned_data <span class="sc">%&gt;%</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(category) <span class="sc">%&gt;%</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_goal =</span> <span class="fu">mean</span>(goal),</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_donators =</span> <span class="fu">mean</span>(number_of_donators),</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_FB_shares =</span> <span class="fu">mean</span>(FB_shares),</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_GFM_hearts =</span> <span class="fu">mean</span>(GFM_hearts)</span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Reorder categories based on mean number of donations</span></span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a>category_performance <span class="ot">&lt;-</span> category_performance <span class="sc">%&gt;%</span></span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">category =</span> <span class="fu">factor</span>(category, <span class="at">levels =</span> category[<span class="fu">order</span>(<span class="sc">-</span>mean_donators)]))</span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a>category_performance <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(category_performance)</span>
<span id="cb64-16"><a href="#cb64-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-17"><a href="#cb64-17" aria-hidden="true" tabindex="-1"></a>category_performance </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 5
  category  mean_goal mean_donators mean_FB_shares mean_GFM_hearts
  &lt;fct&gt;         &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;           &lt;dbl&gt;
1 Animals      98500          1424           5413.           1367.
2 Business     36416.          117.           438.            117.
3 Charity     171995.          664.          1522.            639.
4 Education    62326.          349.           832.            351.
5 Emergency   152998.         1466.          4214.           1481.
6 Family       77056.          721.          2642.            743.
7 Medical     199736.         1618.          4032            1637.
8 Memorial    112639.         1593.          5915.           1664.
9 Volunteer    46422.          145.           706.            150.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bar chart for mean fundraising goals by category</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(category_performance, <span class="fu">aes</span>(<span class="at">x =</span> category, <span class="at">y =</span> mean_donators)) <span class="sc">+</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>) <span class="sc">+</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Category"</span>, <span class="at">y =</span> <span class="st">"Mean Number of Donations"</span>, </span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Mean Number of Donations by Category"</span>) <span class="sc">+</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="gfm_data_analysis_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove rows with NA values in 'number_of_donators'</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>anova_clean <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(gfm_cleaned_data[, <span class="fu">c</span>(<span class="st">"number_of_donators"</span>, <span class="st">"category"</span>)])</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform one-way ANOVA</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>anova_model <span class="ot">&lt;-</span> <span class="fu">aov</span>(number_of_donators <span class="sc">~</span> category, <span class="at">data =</span> anova_clean)</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df    Sum Sq  Mean Sq F value Pr(&gt;F)    
category      17 4.665e+08 27440067   7.456 &lt;2e-16 ***
Residuals   1213 4.464e+09  3680324                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The results of the ANOVA test with removed NA values in the number_of_donators column show that there is a significant difference in the mean number of donations between the campaign categories (p &lt; 0.001). This confirms that the significant difference observed in the original ANOVA analysis remains even after removing the rows with missing values.</p>
<p>Here’s the interpretation of the updated output:</p>
<p><em>Df (Degrees of Freedom):</em> There are 17 degrees of freedom for the category variable, indicating that there are 17 categories being compared in the ANOVA test. The residual degrees of freedom (1213) represent the error degrees of freedom.</p>
<p><em>Sum Sq (Sum of Squares):</em> This represents the variability explained by the category variable and the residuals. For the category variable, the sum of squares is 4.665e+08, indicating the total variability in the mean number of donations explained by the categories. The sum of squares for residuals is 4.464e+09, representing the unexplained variability or error.</p>
<p><em>Mean Sq (Mean Square):</em> This is the sum of squares divided by the degrees of freedom. It represents the average variability within each group (category) or within the residuals.</p>
<p><em>F value:</em> The F value is the test statistic for the ANOVA test. It compares the variability between groups (category) to the variability within groups (residuals). A larger F value indicates a larger difference between group means relative to within-group variability.</p>
<p><em>Pr(&gt;F):</em> This is the p-value associated with the F value. It represents the probability of observing the data if the null hypothesis (no difference between group means) is true. A p-value less than the chosen significance level (typically 0.05) indicates that the null hypothesis can be rejected, suggesting that there is a significant difference between group means.</p>
<p>In this case, the p-value (Pr(&gt;F)) is less than 0.001, indicating strong evidence against the null hypothesis. Therefore, we conclude that there is a significant difference in the mean number of donations between the campaign categories.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>