---
title: "Courses Analysis"
author: "Matthew Roohan (mlr287), Aishwarya Gupta (ag2469), Ryun Shim, Helena Xiong"
format: html
editor: visual
---

## Data and packages

We start with loading the packages we'll use.

```{r}
#| label: load-packages
library(tidyverse)
library(dplyr)
library(ggplot2)
library(tidytext)
library(jsonlite)
```

```{r}
#| label: import-data

coursera_data <- read.csv("data/Coursera.csv")
udemy_data <- read.csv("data/Udemy.csv")
edx_data <- read.csv("data/edx.csv")
skillshare_data <- read.csv("data/skillshare.csv")
```

Analysis on the following:

1.  Coursera
    1.  Distribution of Ratings
    2.  Distribution of course levels
    3.  Ratings vs review
    4.  Distribution of certification type
    5.  Top 25 skills, along with counts

```{r}

course_freq <- coursera_data %>%
  group_by(course) %>%
  summarise(Frequency = n()) %>%
  arrange(desc(Frequency)) %>%
  head(15) 

ggplot(course_freq, aes(x = Frequency, y = reorder(course, Frequency))) +
  geom_bar(stat = "identity", fill = "blue", alpha = 0.7) +
  labs(title = "Top 15 Courses by Frequency",
       x = "Frequency",
       y = "Course") +
  theme_minimal() +
  theme(axis.text.y = element_text(hjust = 1))

```

```{r}
cert_freq <- coursera_data %>%
  group_by(certificatetype) %>%
  summarise(Frequency = n()) %>%
  arrange(desc(Frequency))

ggplot(cert_freq, aes(x = reorder(certificatetype, -Frequency), y = Frequency)) +
  geom_bar(stat = "identity", fill = "blue", alpha = 0.7) +
  geom_text(aes(label = Frequency), vjust = -0.5, size = 3) +  
  labs(title = "Frequency of Certification Types",
       x = "Certification Type",
       y = "Frequency") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10)) 

```

```{r}


clean_skills <- function(x) {
  # If 'x' is NA (missing), return an empty character vector
  if (is.na(x)) {
    return(character(0))
  } else {
    # Otherwise, clean up the 'skills' string and split it into individual skills
    skills <- strsplit(gsub("[{}\"]", "", x), ",\\s*")[[1]]
    return(skills)
  }
}

# Apply the function to clean the skills column
coursera_data$skills <- lapply(coursera_data$skills, clean_skills)

# Unnest the 'skills' column to create a list of all skills
all_skills <- unlist(coursera_data$skills)

# Create a data frame for skills and their frequencies
skills_df <- as.data.frame(table(all_skills))

# Rename the columns
names(skills_df) <- c('Skill', 'Frequency')

# Plot the top N skills
top_n_skills <- 25
ggplot(skills_df[1:top_n_skills, ], aes(x=reorder(Skill, -Frequency), y=Frequency)) +
  geom_bar(stat="identity", fill='blue') +
  coord_flip() + # Flip the coordinates to have skills on the Y axis
  labs(title=paste('Top', top_n_skills, 'Most Common Skills Across Courses'),
       x='Frequency',
       y='Skill') +
  theme_minimal()
```
